---
ID: "83c3565d-59b4-4d83-84cb-b1387761efe3"
Parent: "b43b6148-d5ba-4894-8178-bde628517211"
Template: "b43b6148-d5ba-4894-8178-bde628517211"
Path: /sitecore/templates/Feature/SitecoreShade/TrainingList/Training/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220320T102403Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8108a1ad-a438-4e38-96c2-7a9295b6c1d7"
    - ID: "a30e63d6-ea8e-4e18-ba8d-8cb0433f9fbe"
      Hint: TrainingTitle
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220320T102409Z
